<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TCs.TestCasesPythonOrg-20250416145809" tests="3" file="TCs.py" time="40.516" timestamp="2025-04-16T14:58:50" failures="0" errors="0" skipped="0">
	<testcase classname="TCs.TestCasesPythonOrg" name="test_SearchNoResultsFound" time="17.008" timestamp="2025-04-16T14:58:26" file="TCs.py" line="46">
		<system-out><![CDATA[TC002: Search - no results found passed
]]></system-out>
	</testcase>
	<testcase classname="TCs.TestCasesPythonOrg" name="test_UpcomingEventsSectionPresentInAboutPage" time="12.599" timestamp="2025-04-16T14:58:39" file="TCs.py" line="68">
		<system-out><![CDATA[TC003: Upcoming Events section is present in about page passed
]]></system-out>
	</testcase>
	<testcase classname="TCs.TestCasesPythonOrg" name="test_VerifyPython3DocsButton" time="10.909" timestamp="2025-04-16T14:58:50" file="TCs.py" line="25">
		<system-out><![CDATA[TC001: redirected to correct page Python 3 Docs passed
]]></system-out>
	</testcase>
</testsuite>
